name: ci

run-name: Continuous integration

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies using npm
        run: npm ci

      - name: Check the formatting
        run: npm run format:check

      - name: Run the linter
        run: npm run lint

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies using npm
        run: npm ci

      - name: Run unit tests using Jest
        run: npm run test

  # Based on https://playwright.dev/docs/ci#github-actions
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies using npm
        run: npm ci

      - name: Install dependencies for Playwright
        run: npx playwright install --with-deps

      - name: Build production version of the app
        run: npm run build

      - name: Run end-to-end tests using Playwright
        run: npm run test:e2e
